spring:
  datasource:
    url: jdbc:h2:file:${user.dir}\\db\\auto-irrigation
    username: sa
    password: password
    hikari:
      maximum-pool-size: 30
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.show_sql: true
    show-sql: true
    generate-ddl: false
server:
  servlet:
    context-path: /api/
springdoc:
  api-docs:
    groups:
      enabled: true
  packages-to-scan: com.banquemisr.autoirrigation